// Generated by https://quicktype.io

export interface PokemonListResponse {
  count: number;
  next?: string;
  previous?: string;
  results: SmallPakemon[];
}

export interface SmallPakemon {
  name: string;
  url: string;
  id: number;
  img: string;
}
